name: CI

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - uses: taiki-e/install-action@wasm-pack

      - run: cargo generate-lockfile

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: wasm-pack build --target web

      - name: Run tests
        run: wasm-pack test --node

      - name: Check npm package
        run: cd pkg && npm publish --dry-run
