name: Build wasm

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wasm pack # To fix bug: https://github.com/rustwasm/wasm-pack/issues/837
        run: cargo install --git https://github.com/rustwasm/wasm-pack.git || true

      - name: Build
        run: wasm-pack build

      - name: Run tests
        run: wasm-pack test --node

      - name: Check npm package
        run: cd pkg && npm publish --dry-run
